spring:
  application:
  name: spring-cloud-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sonurepos91/environment-variable-repo
          skipSslValidation: true
          timeout: 5
          clone-on-start: true

server:
  port: 8887